final List<Map<String, String>> countryCodes = [
  {'name': 'Italy', 'code': '+39', 'flag': '🇮🇹'},
  {'name': 'USA/Canada', 'code': '+1', 'flag': '🇺🇸'},
  {'name': 'United Kingdom', 'code': '+44', 'flag': '🇬🇧'},
  {'name': 'Germany', 'code': '+49', 'flag': '🇩🇪'},
  {'name': 'France', 'code': '+33', 'flag': '🇫🇷'},
  {'name': 'Spain', 'code': '+34', 'flag': '🇪🇸'},
  {'name': 'Australia', 'code': '+61', 'flag': '🇦🇺'},
  {'name': 'India', 'code': '+91', 'flag': '🇮🇳'},
  {'name': 'Japan', 'code': '+81', 'flag': '🇯🇵'},
  {'name': 'China', 'code': '+86', 'flag': '🇨🇳'},
  {'name': 'Brazil', 'code': '+55', 'flag': '🇧🇷'},
  {'name': 'South Africa', 'code': '+27', 'flag': '🇿🇦'},
  {'name': 'Mexico', 'code': '+52', 'flag': '🇲🇽'},
  {'name': 'Russia', 'code': '+7', 'flag': '🇷🇺'},
];
