name: isyfit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # --- TUOI PACCHETTI ---
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  firebase_app_check: ^0.3.1
  image_picker: ^1.1.2
  dropdown_button2: ^2.0.0
  animated_text_kit: ^4.2.1
  shared_preferences: ^2.3.5
  file_picker: ^8.1.7
  flutter_pdfview: ^1.4.0
  path_provider: ^2.1.5
  http: ^1.2.2
  intl: ^0.20.1
  fl_chart: ^0.70.2
  webview_flutter: ^4.10.0
  pdf: ^3.11.3
  printing: ^5.14.2
  url_launcher: ^6.2.6
  app_links: ^6.4.0
  flutter_stripe: ^11.5.0
  flutter_riverpod: ^2.6.1
  flutter_local_notifications: ^19.3.0

  # --- NUOVO: runtime per il builder usato ---
  json_annotation: ^4.9.0         # ← NEW
  top_snackbar_flutter: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.3
  integration_test:
    sdk: flutter
  # --- NUOVO: tool di code-generation e builder effettivo ---
  build_runner: ^2.4.11           # ← NEW
  json_serializable: ^6.7.1       # ← NEW
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true                  # lascia attivo: serve a gen-l10n
  uses-material-design: true

  assets:
    - assets/images/ISYFIT_LOGO_new-removebg-resized.png
    - assets/images/silhoutte.png
    - assets/images/woman_silhouette_back.jpg
    - assets/images/woman_silhouette_front.jpg
    - assets/images/woman_silhouette_lateral_left.jpg
    - assets/images/woman_silhouette_lateral_right.jpg
    - assets/images/man_silhouette_back.jpg
    - assets/images/man_silhouette_front.jpg
    - assets/images/man_silhouette_lateral_left.jpg
    - assets/images/man_silhouette_lateral_right.jpg
    - assets/images/swipe_up-removebg.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ISYFIT_LOGO_new-removebg-resized.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/ISYFIT_LOGO_new-removebg-resized.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/ISYFIT_LOGO_new-removebg-resized.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/ISYFIT_LOGO_new-removebg-resized.png"
