// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNoz8B7YBPLruHIZZlp-qvL5RwMMHZ_0I',
    appId: '1:1069724920406:web:928a3fa29f8c4b8e6829f7',
    messagingSenderId: '1069724920406',
    projectId: 'isyfit',
    authDomain: 'isyfit.firebaseapp.com',
    storageBucket: 'isyfit.firebasestorage.app',
    measurementId: 'G-9HVVEDCJVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKIrhmiKqQmO9all3gQlNLQBC2kapHP8Y',
    appId: '1:1069724920406:android:2dc70be396ecf0d46829f7',
    messagingSenderId: '1069724920406',
    projectId: 'isyfit',
    storageBucket: 'isyfit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMrrlZD_u3tHSS5us_uLcKXGVQ9pK_XzA',
    appId: '1:1069724920406:ios:130a498fdde2ea5a6829f7',
    messagingSenderId: '1069724920406',
    projectId: 'isyfit',
    storageBucket: 'isyfit.firebasestorage.app',
    iosBundleId: 'com.isyfit.app',
  );
}
